# Generated by Django 4.2.5 on 2023-11-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('bloque_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_c', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('modulo_id', models.IntegerField()),
                ('id_jefe', models.IntegerField()),
                ('jornada_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarrMod',
            fields=[
                ('carre_mod_id', models.IntegerField(primary_key=True, serialize=False)),
                ('modulo_id', models.IntegerField()),
                ('id_carrera', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('dia_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DispDocente',
            fields=[
                ('disp_doc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_docente', models.IntegerField()),
                ('bloque_id', models.IntegerField()),
                ('jornada_id', models.IntegerField()),
                ('estado_id', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.IntegerField(primary_key=True, serialize=False)),
                ('d_nombre', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=15, null=True)),
                ('jornada_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estado_id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_hora', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstMod',
            fields=[
                ('id_est_mod', models.IntegerField(primary_key=True, serialize=False)),
                ('est_id', models.IntegerField()),
                ('modulo_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('est_id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('estado_id', models.IntegerField(blank=True, null=True)),
                ('est_nombre', models.CharField(blank=True, max_length=10, null=True)),
                ('email_est', models.CharField(blank=True, max_length=10, null=True)),
                ('modulo_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('horario_id', models.IntegerField(primary_key=True, serialize=False)),
                ('jornada_id', models.IntegerField()),
                ('estado_id', models.IntegerField()),
                ('horario_year', models.IntegerField(blank=True, null=True)),
                ('bloque_id', models.IntegerField()),
                ('sala_id', models.IntegerField()),
                ('modulo_id', models.IntegerField()),
                ('dia_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JefeCarrera',
            fields=[
                ('id_jefe', models.IntegerField(primary_key=True, serialize=False)),
                ('id_docente', models.IntegerField(blank=True, null=True)),
                ('estado_id', models.IntegerField(blank=True, null=True)),
                ('nombre_jefe', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=10, null=True)),
                ('sala_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('jornada_id', models.IntegerField(primary_key=True, serialize=False)),
                ('jor_inscrip', models.CharField(blank=True, max_length=20, null=True)),
                ('jor_horario', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('diurna', models.CharField(blank=True, max_length=255, null=True)),
                ('vespertina', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModDoc',
            fields=[
                ('id_mod_doc', models.IntegerField(primary_key=True, serialize=False)),
                ('modulo_id', models.IntegerField()),
                ('id_docente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('modulo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mod_nombre', models.CharField(blank=True, max_length=1, null=True)),
                ('tipo_j', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_hora', models.IntegerField(blank=True, null=True)),
                ('estado_id', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('sala_id', models.IntegerField(primary_key=True, serialize=False)),
                ('capacidad_sala', models.IntegerField(blank=True, null=True)),
                ('sala_tipo', models.CharField(blank=True, max_length=10, null=True)),
                ('id_usuario', models.IntegerField()),
                ('estado_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id_semestre', models.IntegerField(primary_key=True, serialize=False)),
                ('sem_ano', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.IntegerField(blank=True, null=True)),
                ('estado_id', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id_test', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_test', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
