# Generated by Django 4.2.5 on 2023-11-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinc_informe_3', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
