# Generated by Django 4.2.5 on 2023-11-30 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinc_informe_3', '0002_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispdocente',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='semestre',
            name='id_usuario',
        ),
    ]
