# Generated by Django 4.2.5 on 2023-11-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinc_informe_3', '0007_alter_carrera_nombre_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='email_est',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
