# Generated by Django 4.2.5 on 2023-11-30 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinc_informe_3', '0008_remove_estudiante_email_est_estudiante_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modulo',
            new_name='sinc_informe_3_modulo',
        ),
    ]
